### ISSUE TITLE
Trouble downloading large episodes (Dan Carlin's Hardcore History)

### ISSUE THREAD

**Issue by runical** [CarolusMagnus/Podcatcher#10] opened 2016-09-02 15:35 UTC
I'm having trouble with downloading Dan Carlin's Hardcore History. The files download just fine, but podcatcher crashes right after downloading the episode (which is 200+ MB large). This crash also seems to delete all other references to the file, so after downloading the file and crashing, the file is gone. All other feeds seem to work just fine, so I'm led to believe that this is an issue with the large filesize.

As for my phone, I have a Jolla 1 with the latest stable SailfishOS (2.0.1.11). If you need more information, please ask.

**Comment by CarolusMagnus** [comment] 2016-09-03 17:39
I can confirm this problem. It looks like there is too much memory being allocated before writing the file to disk.

**Comment by CarolusMagnus** [comment] 2016-09-04 16:16
This should be fixed now. Soon I will upload the new release on Jolla Harbour.

**Closed** 2020-05-03 17:12 UTC
